enum SYS_UI_MESSAGES{
	SYS_UI_MSG_NO_HDD	= 0,
	SYS_UI_MSG_PLEASE_WAIT,
	SYS_UI_MSG_HDD_FAULT,
	SYS_UI_MSG_SCAN_DISK_COMPLETED_OK,
	SYS_UI_MSG_AUTO_SCAN_DISK_CFM,

	SYS_UI_MSG_COUNT
};

enum SYS_UI_LABEL_TEXT{
	SYS_UI_LBL_OK	= 0,
	SYS_UI_LBL_CANCEL,
	SYS_UI_LBL_YES,
	SYS_UI_LBL_NO,
	SYS_UI_LBL_NEXT,
	SYS_UI_LBL_BACK,
	SYS_UI_LBL_ABORT,
	SYS_UI_LBL_WARNING,
	SYS_UI_LBL_ERROR,
	SYS_UI_LBL_INFO,
	SYS_UI_LBL_CONFIRM,
	SYS_UI_LBL_WAIT,
	SYS_UI_LBL_SCAN_RESULTS,

	SYS_UI_LBL_COUNT
};
